# Generated by Django 5.0.3 on 2024-04-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tareasApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tarea",
            new_name="tareas",
        ),
    ]
